fdfs:
  so-timeout: 1501 # 链接超时
  connect-timeout: 601 # 读取时间
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:
    - localhost:22123
  web-server-url: localhost:7899
  pool:
    #从池中借出的对象的最大数目（配置为-1表示不限制）
    max-total: -1
    #获取连接时的最大等待毫秒数(默认配置为5秒)
    max-wait-millis: 5000
    #每个key最大连接数
    max-total-per-key: 50
    #每个key对应的连接池最大空闲连接数
    max-idle-per-key: 10
    #每个key对应的连接池最小空闲连接数
    min_idle_per_key: 5
