server:
  port: 8001
eureka:
  instance:
    hostname: localhost
  client:
    # 不向注册中心注册自己 （单机模式为false）
    register-with-eureka: false
    # 是否拉取其它服务的信息，默认是true（单机模式为false）
    fetch-registry: false
    # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    # 关闭注册中心的保护机制，默认是开启 (正式环境建议开启)
    enable-self-preservation: false
