server:
  port: 8002
spring:
  application:
    # 服务名称
    name: demo-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
    healthcheck:
      enabled: true
