spring:
  datasource:
    one:
      jdbc-url: jdbc:mysql://localhost:3306/db1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CST&useAffectedRows=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      pool-name: DatebookHikariCPOne
      # 使用hikari连接池
      type: com.zaxxer.hikari.HikariDataSource
      minimum-idle: 1
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    two:
      jdbc-url: jdbc:oracle:thin:@//localhost:1521/orcl
      driver-class-name: oracle.jdbc.OracleDriver
      username: db2
      password: db2
      pool-name: DatebookHikariCPTwo
      type: com.zaxxer.hikari.HikariDataSource
      #指定连接维护的最小空闲连接数，当使用HikariCP时指定.
      minimum-idle: 1
      #指定连接池最大的连接数，包括使用中的和空闲的连接.
      maximum-pool-size: 8
      #指定校验连接合法性执行的sql语句
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual
